site_name: DevOps Foundation Course for ZeOmega

site_author: Anand Chitpothu
copyright: Copyright Â© 2022, Pipal Academy

theme:
  name: material
  features:
    - navigation.tabs

nav:
  - Introduction:
    - index.md
    - outline.md
    - lab-setup.md
  - Managing Servers:
    - managing-servers.md
