site_name: DevOps Foundation Course for ZeOmega

site_author: Anand Chitpothu
copyright: Copyright Â© 2022, Pipal Academy

theme:
  name: material
  features:
    - navigation.tabs

nav:
  - Introduction:
    - index.md
    - outline.md
    - lab-setup.md
  - Managing Servers:
    - managing-servers.md
  - Docker:
    - docker/introduction.md
    - docker/registry.md
    - docker/environment.md
    - docker/ports.md
    - docker/volumes.md
    - docker/cheatsheet.md
    - docker/diving-in.md
    - docker/docker-compose.md
    - docker/best-practices.md
  - Kubernetes:
    - kubernetes/introduction.md
    - kubernetes/pods.md
    - kubernetes/deployments.md
    - kubernetes/services.md
    - kubernetes/ingress.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences